Firmware SDK: bc_ds18b20
bc_ds18b20
Driver for 1wire ds18b20.
Typedefs
typedef struct bc_ds18b20_t bc_ds18b20_t
BigClown ds18b20 instance.
typedef struct bc_ds18b20_sensor_t bc_ds18b20_sensor_t
Enumerations
enum bc_ds18b20_event_t {
BC_DS18B20_EVENT_ERROR = -1,
BC_DS18B20_EVENT_UPDATE = 0
}
Callback events.
Functions
void bc_ds18b20_init_single (bc_ds18b20_t *self, bc_ds18b20_resolution_bits_t resolution)
Initialize single ds18b20 over channel B on Sensor Module.
void bc_ds18b20_init_multiple (bc_ds18b20_t *self, bc_ds18b20_sensor_t *sensors, int sensor_count, bc_ds18b20_resolution_bits_t resolution)
Initialize multiple ds18b20 over channel B on Sensor Module.
void bc_ds18b20_init (bc_ds18b20_t *self, bc_gpio_channel_t onewire_channel, bc_ds18b20_sensor_t *sensors, int sensor_count, bc_ds18b20_resolution_bits_t resolution)
Initialize ds18b20.
void bc_ds18b20_set_event_handler (bc_ds18b20_t *self, void(*event_handler)(bc_ds18b20_t *, uint64_t _device_address, bc_ds18b20_event_t, void *), void *event_param)
Set callback function.
void bc_ds18b20_set_update_interval (bc_ds18b20_t *self, bc_tick_t interval)
Set measurement interval.
bool bc_ds18b20_measure (bc_ds18b20_t *self)
Start measurement manually.
bool bc_ds18b20_get_temperature_raw (bc_ds18b20_t *self, uint64_t device_address, int16_t *raw)
Get measured temperature in degrees of Celsius.
bool bc_ds18b20_get_temperature_celsius (bc_ds18b20_t *self, uint64_t _device_address, float *celsius)
Get measured temperature in degrees of Celsius.
int bc_ds18b20_get_index_by_device_address (bc_ds18b20_t *self, uint64_t device_address)
Get device index by its device address.
int bc_ds18b20_get_sensor_found (bc_ds18b20_t *self)
Get number of found sensor.
void bc_ds18b20_set_power_dynamic (bc_ds18b20_t *self, bool on)
Set power dynamic, Turns VDD on and pull 4k7 only for measurement.
Detailed Description
Driver for 1wire ds18b20.
Enumeration Type Documentation
enum bc_ds18b20_event_t
Callback events.
Enumerator
BC_DS18B20_EVENT_ERROR
Error event.
BC_DS18B20_EVENT_UPDATE
Update event.
Definition at line 15 of file bc_ds18b20.h.
Function Documentation
int bc_ds18b20_get_index_by_device_address (bc_ds18b20_t * self, uint64_t device_address)
Get device index by its device address.
Parameters
[in] self Instance
[in] device_address 64b device address
Definition at line 85 of file bc_ds18b20.c.
Referenced by bc_ds18b20_get_temperature_celsius(), and bc_ds18b20_get_temperature_raw().
int bc_ds18b20_get_sensor_found (bc_ds18b20_t * self)
Get number of found sensor.
Parameters
[in] self Instance
Definition at line 98 of file bc_ds18b20.c.
bool bc_ds18b20_get_temperature_celsius (bc_ds18b20_t * self, uint64_t _device_address, float * celsius)
Get measured temperature in degrees of Celsius.
Parameters
[in] self Instance
[in] device_address 64b device address
[in] celsius Pointer to variables where results will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 127 of file bc_ds18b20.c.
bool bc_ds18b20_get_temperature_raw (bc_ds18b20_t * self, uint64_t device_address, int16_t * raw)
Get measured temperature in degrees of Celsius.
Parameters
[in] self Instance
[in] device_address 64b device address Get measured temperature as raw values
Returns
true When value is valid
false When value is invalid
Definition at line 108 of file bc_ds18b20.c.
void bc_ds18b20_init (bc_ds18b20_t * self, bc_gpio_channel_t onewire_channel, bc_ds18b20_sensor_t * sensors, int sensor_count, bc_ds18b20_resolution_bits_t resolution)
Initialize ds18b20.
Parameters
[in] self Instance
[in] onewire_channel GPIO channel
[in] sensors Sensor array
[in] sensor_count Max count sensors
[in] resolution Resolution
Definition at line 32 of file bc_ds18b20.c.
Referenced by bc_ds18b20_init_multiple().
void bc_ds18b20_init_multiple (bc_ds18b20_t * self, bc_ds18b20_sensor_t * sensors, int sensor_count, bc_ds18b20_resolution_bits_t resolution)
Initialize multiple ds18b20 over channel B on Sensor Module.
Parameters
[in] self Instance
[in] sensors Sensor array
[in] sensor_count Max count sensors
[in] resolution Resolution
Definition at line 27 of file bc_ds18b20.c.
Referenced by bc_ds18b20_init_single().
void bc_ds18b20_init_single (bc_ds18b20_t * self, bc_ds18b20_resolution_bits_t resolution)
Initialize single ds18b20 over channel B on Sensor Module.
Parameters
[in] self Instance
[in] resolution Resolution
Definition at line 21 of file bc_ds18b20.c.
bool bc_ds18b20_measure (bc_ds18b20_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
false When other measurement is in progress
Definition at line 71 of file bc_ds18b20.c.
Referenced by bc_ds18b20_set_update_interval().
void bc_ds18b20_set_event_handler (bc_ds18b20_t * self, void(*)(bc_ds18b20_t *, uint64_t _device_address, bc_ds18b20_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 48 of file bc_ds18b20.c.
void bc_ds18b20_set_power_dynamic (bc_ds18b20_t * self, bool on)
Set power dynamic, Turns VDD on and pull 4k7 only for measurement.
Parameters
[in] self Instance
[in] on True enable dynamic, False disable dynamic
Definition at line 103 of file bc_ds18b20.c.
void bc_ds18b20_set_update_interval (bc_ds18b20_t * self, bc_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 55 of file bc_ds18b20.c.